name: Publish to JitPack

on:
  push:
    tags:
      - 'v*.*.*'  # v1.0.0, v1.2.3 などのタグにマッチ

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Run Unit Tests
        run: ./gradlew test
      
      - name: Run Lint
        run: ./gradlew lint
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/reports/tests/

  build:
    name: Build Library
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build library
        run: ./gradlew assembleRelease
      
      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: library-aar
          path: app/build/outputs/aar/*.aar

  publish:
    name: Publish to JitPack
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Publish to Maven Local
        run: ./gradlew publishToMavenLocal
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/aar/*.aar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Trigger JitPack build
        run: |
          curl -X POST "https://jitpack.io/api/builds/com.github.segnities007/mvi/${{ steps.get_version.outputs.VERSION }}"
      
      - name: Comment on commit
        uses: actions/github-script@v7
        with:
          script: |
            const version = '${{ steps.get_version.outputs.VERSION }}';
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: `✅ Successfully published version ${version} to JitPack!\n\n` +
                    `[![](https://jitpack.io/v/com.github.segnities007/mvi.svg)](https://jitpack.io/#com.github.segnities007/mvi)\n\n` +
                    `Add to your project:\n` +
                    `\`\`\`gradle\n` +
                    `dependencies {\n` +
                    `    implementation("com.github.segnities007:mvi:${version}")\n` +
                    `}\n` +
                    `\`\`\``
            })
